# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/herr/Archiwum/Programów/projekty kdevelop/nocturn"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/herr/Archiwum/Programów/projekty kdevelop/nocturn"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/herr/Archiwum/Programów/projekty kdevelop/nocturn/CMakeFiles" "/home/herr/Archiwum/Programów/projekty kdevelop/nocturn/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/herr/Archiwum/Programów/projekty kdevelop/nocturn/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nocturn

# Build rule for target.
nocturn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nocturn
.PHONY : nocturn

# fast build rule for target.
nocturn/fast:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/build
.PHONY : nocturn/fast

#=============================================================================
# Target rules for targets named nocturn_automoc

# Build rule for target.
nocturn_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nocturn_automoc
.PHONY : nocturn_automoc

# fast build rule for target.
nocturn_automoc/fast:
	$(MAKE) -f CMakeFiles/nocturn_automoc.dir/build.make CMakeFiles/nocturn_automoc.dir/build
.PHONY : nocturn_automoc/fast

audiotrackmodel.o: audiotrackmodel.cpp.o
.PHONY : audiotrackmodel.o

# target to build an object file
audiotrackmodel.cpp.o:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/audiotrackmodel.cpp.o
.PHONY : audiotrackmodel.cpp.o

audiotrackmodel.i: audiotrackmodel.cpp.i
.PHONY : audiotrackmodel.i

# target to preprocess a source file
audiotrackmodel.cpp.i:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/audiotrackmodel.cpp.i
.PHONY : audiotrackmodel.cpp.i

audiotrackmodel.s: audiotrackmodel.cpp.s
.PHONY : audiotrackmodel.s

# target to generate assembly for a file
audiotrackmodel.cpp.s:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/audiotrackmodel.cpp.s
.PHONY : audiotrackmodel.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/main.cpp.s
.PHONY : main.cpp.s

maincontroler.o: maincontroler.cpp.o
.PHONY : maincontroler.o

# target to build an object file
maincontroler.cpp.o:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/maincontroler.cpp.o
.PHONY : maincontroler.cpp.o

maincontroler.i: maincontroler.cpp.i
.PHONY : maincontroler.i

# target to preprocess a source file
maincontroler.cpp.i:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/maincontroler.cpp.i
.PHONY : maincontroler.cpp.i

maincontroler.s: maincontroler.cpp.s
.PHONY : maincontroler.s

# target to generate assembly for a file
maincontroler.cpp.s:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/maincontroler.cpp.s
.PHONY : maincontroler.cpp.s

mainview.o: mainview.cpp.o
.PHONY : mainview.o

# target to build an object file
mainview.cpp.o:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/mainview.cpp.o
.PHONY : mainview.cpp.o

mainview.i: mainview.cpp.i
.PHONY : mainview.i

# target to preprocess a source file
mainview.cpp.i:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/mainview.cpp.i
.PHONY : mainview.cpp.i

mainview.s: mainview.cpp.s
.PHONY : mainview.s

# target to generate assembly for a file
mainview.cpp.s:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/mainview.cpp.s
.PHONY : mainview.cpp.s

modelmanager.o: modelmanager.cpp.o
.PHONY : modelmanager.o

# target to build an object file
modelmanager.cpp.o:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/modelmanager.cpp.o
.PHONY : modelmanager.cpp.o

modelmanager.i: modelmanager.cpp.i
.PHONY : modelmanager.i

# target to preprocess a source file
modelmanager.cpp.i:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/modelmanager.cpp.i
.PHONY : modelmanager.cpp.i

modelmanager.s: modelmanager.cpp.s
.PHONY : modelmanager.s

# target to generate assembly for a file
modelmanager.cpp.s:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/modelmanager.cpp.s
.PHONY : modelmanager.cpp.s

nocturn.o: nocturn.cpp.o
.PHONY : nocturn.o

# target to build an object file
nocturn.cpp.o:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/nocturn.cpp.o
.PHONY : nocturn.cpp.o

nocturn.i: nocturn.cpp.i
.PHONY : nocturn.i

# target to preprocess a source file
nocturn.cpp.i:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/nocturn.cpp.i
.PHONY : nocturn.cpp.i

nocturn.s: nocturn.cpp.s
.PHONY : nocturn.s

# target to generate assembly for a file
nocturn.cpp.s:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/nocturn.cpp.s
.PHONY : nocturn.cpp.s

nocturn_automoc.o: nocturn_automoc.cpp.o
.PHONY : nocturn_automoc.o

# target to build an object file
nocturn_automoc.cpp.o:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/nocturn_automoc.cpp.o
.PHONY : nocturn_automoc.cpp.o

nocturn_automoc.i: nocturn_automoc.cpp.i
.PHONY : nocturn_automoc.i

# target to preprocess a source file
nocturn_automoc.cpp.i:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/nocturn_automoc.cpp.i
.PHONY : nocturn_automoc.cpp.i

nocturn_automoc.s: nocturn_automoc.cpp.s
.PHONY : nocturn_automoc.s

# target to generate assembly for a file
nocturn_automoc.cpp.s:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/nocturn_automoc.cpp.s
.PHONY : nocturn_automoc.cpp.s

playbackmanager.o: playbackmanager.cpp.o
.PHONY : playbackmanager.o

# target to build an object file
playbackmanager.cpp.o:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/playbackmanager.cpp.o
.PHONY : playbackmanager.cpp.o

playbackmanager.i: playbackmanager.cpp.i
.PHONY : playbackmanager.i

# target to preprocess a source file
playbackmanager.cpp.i:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/playbackmanager.cpp.i
.PHONY : playbackmanager.cpp.i

playbackmanager.s: playbackmanager.cpp.s
.PHONY : playbackmanager.s

# target to generate assembly for a file
playbackmanager.cpp.s:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/playbackmanager.cpp.s
.PHONY : playbackmanager.cpp.s

playbackmodel.o: playbackmodel.cpp.o
.PHONY : playbackmodel.o

# target to build an object file
playbackmodel.cpp.o:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/playbackmodel.cpp.o
.PHONY : playbackmodel.cpp.o

playbackmodel.i: playbackmodel.cpp.i
.PHONY : playbackmodel.i

# target to preprocess a source file
playbackmodel.cpp.i:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/playbackmodel.cpp.i
.PHONY : playbackmodel.cpp.i

playbackmodel.s: playbackmodel.cpp.s
.PHONY : playbackmodel.s

# target to generate assembly for a file
playbackmodel.cpp.s:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/playbackmodel.cpp.s
.PHONY : playbackmodel.cpp.s

playbackphonon.o: playbackphonon.cpp.o
.PHONY : playbackphonon.o

# target to build an object file
playbackphonon.cpp.o:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/playbackphonon.cpp.o
.PHONY : playbackphonon.cpp.o

playbackphonon.i: playbackphonon.cpp.i
.PHONY : playbackphonon.i

# target to preprocess a source file
playbackphonon.cpp.i:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/playbackphonon.cpp.i
.PHONY : playbackphonon.cpp.i

playbackphonon.s: playbackphonon.cpp.s
.PHONY : playbackphonon.s

# target to generate assembly for a file
playbackphonon.cpp.s:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/playbackphonon.cpp.s
.PHONY : playbackphonon.cpp.s

playlistmanager.o: playlistmanager.cpp.o
.PHONY : playlistmanager.o

# target to build an object file
playlistmanager.cpp.o:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/playlistmanager.cpp.o
.PHONY : playlistmanager.cpp.o

playlistmanager.i: playlistmanager.cpp.i
.PHONY : playlistmanager.i

# target to preprocess a source file
playlistmanager.cpp.i:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/playlistmanager.cpp.i
.PHONY : playlistmanager.cpp.i

playlistmanager.s: playlistmanager.cpp.s
.PHONY : playlistmanager.s

# target to generate assembly for a file
playlistmanager.cpp.s:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/playlistmanager.cpp.s
.PHONY : playlistmanager.cpp.s

playlistmodel.o: playlistmodel.cpp.o
.PHONY : playlistmodel.o

# target to build an object file
playlistmodel.cpp.o:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/playlistmodel.cpp.o
.PHONY : playlistmodel.cpp.o

playlistmodel.i: playlistmodel.cpp.i
.PHONY : playlistmodel.i

# target to preprocess a source file
playlistmodel.cpp.i:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/playlistmodel.cpp.i
.PHONY : playlistmodel.cpp.i

playlistmodel.s: playlistmodel.cpp.s
.PHONY : playlistmodel.s

# target to generate assembly for a file
playlistmodel.cpp.s:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/playlistmodel.cpp.s
.PHONY : playlistmodel.cpp.s

playlistpageview.o: playlistpageview.cpp.o
.PHONY : playlistpageview.o

# target to build an object file
playlistpageview.cpp.o:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/playlistpageview.cpp.o
.PHONY : playlistpageview.cpp.o

playlistpageview.i: playlistpageview.cpp.i
.PHONY : playlistpageview.i

# target to preprocess a source file
playlistpageview.cpp.i:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/playlistpageview.cpp.i
.PHONY : playlistpageview.cpp.i

playlistpageview.s: playlistpageview.cpp.s
.PHONY : playlistpageview.s

# target to generate assembly for a file
playlistpageview.cpp.s:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/playlistpageview.cpp.s
.PHONY : playlistpageview.cpp.s

playlistpageviewitem.o: playlistpageviewitem.cpp.o
.PHONY : playlistpageviewitem.o

# target to build an object file
playlistpageviewitem.cpp.o:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/playlistpageviewitem.cpp.o
.PHONY : playlistpageviewitem.cpp.o

playlistpageviewitem.i: playlistpageviewitem.cpp.i
.PHONY : playlistpageviewitem.i

# target to preprocess a source file
playlistpageviewitem.cpp.i:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/playlistpageviewitem.cpp.i
.PHONY : playlistpageviewitem.cpp.i

playlistpageviewitem.s: playlistpageviewitem.cpp.s
.PHONY : playlistpageviewitem.s

# target to generate assembly for a file
playlistpageviewitem.cpp.s:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/playlistpageviewitem.cpp.s
.PHONY : playlistpageviewitem.cpp.s

taghandler.o: taghandler.cpp.o
.PHONY : taghandler.o

# target to build an object file
taghandler.cpp.o:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/taghandler.cpp.o
.PHONY : taghandler.cpp.o

taghandler.i: taghandler.cpp.i
.PHONY : taghandler.i

# target to preprocess a source file
taghandler.cpp.i:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/taghandler.cpp.i
.PHONY : taghandler.cpp.i

taghandler.s: taghandler.cpp.s
.PHONY : taghandler.s

# target to generate assembly for a file
taghandler.cpp.s:
	$(MAKE) -f CMakeFiles/nocturn.dir/build.make CMakeFiles/nocturn.dir/taghandler.cpp.s
.PHONY : taghandler.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... nocturn"
	@echo "... nocturn_automoc"
	@echo "... rebuild_cache"
	@echo "... audiotrackmodel.o"
	@echo "... audiotrackmodel.i"
	@echo "... audiotrackmodel.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... maincontroler.o"
	@echo "... maincontroler.i"
	@echo "... maincontroler.s"
	@echo "... mainview.o"
	@echo "... mainview.i"
	@echo "... mainview.s"
	@echo "... modelmanager.o"
	@echo "... modelmanager.i"
	@echo "... modelmanager.s"
	@echo "... nocturn.o"
	@echo "... nocturn.i"
	@echo "... nocturn.s"
	@echo "... nocturn_automoc.o"
	@echo "... nocturn_automoc.i"
	@echo "... nocturn_automoc.s"
	@echo "... playbackmanager.o"
	@echo "... playbackmanager.i"
	@echo "... playbackmanager.s"
	@echo "... playbackmodel.o"
	@echo "... playbackmodel.i"
	@echo "... playbackmodel.s"
	@echo "... playbackphonon.o"
	@echo "... playbackphonon.i"
	@echo "... playbackphonon.s"
	@echo "... playlistmanager.o"
	@echo "... playlistmanager.i"
	@echo "... playlistmanager.s"
	@echo "... playlistmodel.o"
	@echo "... playlistmodel.i"
	@echo "... playlistmodel.s"
	@echo "... playlistpageview.o"
	@echo "... playlistpageview.i"
	@echo "... playlistpageview.s"
	@echo "... playlistpageviewitem.o"
	@echo "... playlistpageviewitem.i"
	@echo "... playlistpageviewitem.s"
	@echo "... taghandler.o"
	@echo "... taghandler.i"
	@echo "... taghandler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

